name: tests

on: push

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout asdf-zephyr plugin
        uses: actions/checkout@v4
        with:
          path: plugin
      - name: Install asdf
        uses: actions/checkout@v4
        with:
          repository: asdf-vm/asdf
          path: .asdf
          ref: v0.14.0
      - name: Test asdf-zephyr plugin
        run: |
          source .asdf/asdf.sh
          asdf plugin test zephyr plugin "west --version"
